_wandb:
    value:
        cli_version: 0.23.0
        e:
            scuo28zr8sfeawpmc10v91ll93tqxz81:
                codePath: server.py
                codePathLocal: server.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "244936478720"
                        used: "36636356608"
                email: abhyudaya410@gmail.com
                executable: /home/zeus/miniconda3/envs/cloudspace/bin/python
                git:
                    commit: 254636eab6a4413dd36eeec1d8e818b12c9a2921
                    remote: https://github.com/Abhyu-S/kortex-sdxl.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-117b181c-1ccb-356e-568c-e01eaaa2dc98
                host: ip-10-192-11-225
                memory:
                    total: "16555130880"
                os: Linux-6.8.0-1024-aws-x86_64-with-glibc2.39
                program: /teamspace/studios/this_studio/diffusion_tobeused/server.py
                python: CPython 3.12.11
                root: /teamspace/studios/this_studio/diffusion_tobeused
                startedAt: "2025-12-02T19:06:02.997562Z"
                writerId: scuo28zr8sfeawpmc10v91ll93tqxz81
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 83
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 83
                - 98
            "3":
                - 13
            "4": 3.12.11
            "5": 0.23.0
            "6": 4.57.3
            "12": 0.23.0
            "13": linux-x86_64
