_wandb:
    value:
        cli_version: 0.23.0
        e:
            177ow5bmwhovop6ub78fwctcqyx330wx:
                codePath: server.py
                codePathLocal: server.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "589427720192"
                        used: "60257505280"
                email: abhyudaya410@gmail.com
                executable: /home/zeus/miniconda3/envs/cloudspace/bin/python
                git:
                    commit: 756993a9f60a97b0106d0cc799a9ea4df05f16cb
                    remote: https://github.com/Abhyu-S/diffusion_tobeused
                gpu: NVIDIA L4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7424
                      memoryTotal: "24152899584"
                      name: NVIDIA L4
                      uuid: GPU-03b60cec-f089-97a6-8bb1-883690b9c7f7
                host: ip-10-192-11-111
                memory:
                    total: "64919552000"
                os: Linux-6.8.0-1024-aws-x86_64-with-glibc2.39
                program: /teamspace/studios/this_studio/diffusion_tobeused/server.py
                python: CPython 3.12.11
                root: /teamspace/studios/this_studio/diffusion_tobeused
                startedAt: "2025-12-02T18:19:13.909Z"
                writerId: 177ow5bmwhovop6ub78fwctcqyx330wx
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 83
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 83
                - 98
            "3":
                - 13
            "4": 3.12.11
            "5": 0.23.0
            "6": 4.57.3
            "12": 0.23.0
            "13": linux-x86_64
